"""
Tests for utility functions.
"""

from datetime import datetime, timedelta, timezone

import pytest

from app.utils.time import utc_now_iso


@pytest.mark.asyncio
class TestTimeUtilities:
    """Test cases for time utility functions."""

    def test_utc_now_iso_format(self):
        """Test that utc_now_iso returns valid ISO-8601 format."""
        result = utc_now_iso()

        # Should be parseable as ISO datetime
        parsed = datetime.fromisoformat(result.replace("Z", "+00:00"))

        assert parsed is not None
        assert isinstance(parsed, datetime)

    def test_utc_now_iso_timezone(self):
        """Test that utc_now_iso returns UTC timezone."""
        result = utc_now_iso()

        parsed = datetime.fromisoformat(result.replace("Z", "+00:00"))

        # Should be UTC (timezone offset should be 0)
        assert parsed.utcoffset() == timedelta(0)

    def test_utc_now_iso_recent(self):
        """Test that utc_now_iso returns current time."""
        before = datetime.now(timezone.utc)
        result = utc_now_iso()
        after = datetime.now(timezone.utc)

        parsed = datetime.fromisoformat(result.replace("Z", "+00:00"))

        # Should be between before and after (with some tolerance)
        assert before <= parsed <= after

    def test_utc_now_iso_consistency(self):
        """Test that utc_now_iso returns consistent format."""
        results = [utc_now_iso() for _ in range(10)]

        for result in results:
            # Should have UTC timezone info (+00:00 in Python 3.9)
            assert "+00:00" in result

            # All should have T separator
            assert "T" in result

    def test_utc_now_iso_microseconds(self):
        """Test that utc_now_iso includes microseconds."""
        result = utc_now_iso()

        # Should include microseconds (after decimal point)
        assert "." in result

        # Parse and check microsecond precision
        parsed = datetime.fromisoformat(result.replace("Z", "+00:00"))
        # Microseconds should be present (0-999999)
        assert 0 <= parsed.microsecond < 1000000


@pytest.mark.asyncio
class TestTimeEdgeCases:
    """Test cases for time utility edge cases."""

    def test_multiple_calls_different_times(self):
        """Test that multiple calls return different times."""
        result1 = utc_now_iso()
        result2 = utc_now_iso()

        # Should be slightly different (usually)
        # But they could be the same if called very quickly
        assert result1 is not None
        assert result2 is not None

    def test_format_compatibility(self):
        """Test that format is compatible with common parsers."""
        result = utc_now_iso()

        # Python datetime
        parsed_python = datetime.fromisoformat(result)
        assert parsed_python is not None

        # The format should be ISO-8601 with timezone
        assert "T" in result
        assert "+00:00" in result


@pytest.mark.asyncio
class TestTimeIntegration:
    """Test cases for time utility integration."""

    def test_utc_now_for_timestamps(self):
        """Test using utc_now_iso for object timestamps."""
        timestamp = utc_now_iso()

        # Should be usable in object payloads
        data = {
            "title": "Test",
            "created_at": timestamp,
            "updated_at": timestamp,
        }

        assert data["created_at"] is not None
        assert data["updated_at"] is not None

    def test_utc_now_comparison(self):
        """Test comparing timestamps generated by utc_now_iso."""
        time1 = utc_now_iso()
        time2 = utc_now_iso()

        # time2 should be >= time1
        parsed1 = datetime.fromisoformat(time1.replace("Z", "+00:00"))
        parsed2 = datetime.fromisoformat(time2.replace("Z", "+00:00"))

        assert parsed2 >= parsed1


@pytest.mark.asyncio
class TestOtherUtilities:
    """Test cases for other utility functions (if any)."""

    def test_generate_id(self):
        """Test ID generation utility (if exists)."""
        # This would need an actual generate_id function
        # For now, just test that we can create IDs
        import uuid

        test_id = str(uuid.uuid4())

        assert test_id is not None
        assert len(test_id) == 36  # Standard UUID length

    def test_generate_id_unique(self):
        """Test that generated IDs are unique."""
        import uuid

        ids = [str(uuid.uuid4()) for _ in range(100)]

        # All should be unique
        assert len(set(ids)) == 100
