"""Action outbox — every external write, recorded before it happens
(BUILD_SPEC sections 51, 57, 60, 61).

Section 60's rule is the reason this module exists: *never blind-retry an
external commitment*. Booking an appointment twice is worse than not booking
it, so an Action is persisted with its idempotency key **before** the request
goes out. If LifeOps dies mid-flight, the record is what tells the next run
whether the previous attempt may already have succeeded.

Two properties follow from that and are enforced here rather than by callers:

  * The idempotency key is generated by LifeOps, never by a model (section 61).
    A key an LLM invents is a key that changes when it re-reasons.
  * The payload hash is what an approval binds to (section 57). If the payload
    changes after approval, the hash changes, and the approval no longer
    matches — "material change invalidates approval" becomes arithmetic
    instead of judgement.
"""

from __future__ import annotations

import hashlib
import json
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from lifeops.domain.tasks import VerificationState
from lifeops.errors import ValidationError
from lifeops.ids import new_action_id


class ActionType(StrEnum):
    """The external actions of section 51.

    Narrow and semantic, never ``do_action``: a generic action tool moves the
    decision about what is safe out of policy and into a model's judgement.
    """

    SEND_EMAIL = "send_email"
    REQUEST_QUOTE = "request_quote"
    BOOK_APPOINTMENT = "book_appointment"
    CANCEL_APPOINTMENT = "cancel_appointment"
    PLACE_PHONE_CALL = "place_phone_call"
    BUILD_GROCERY_CART = "build_grocery_cart"
    SUBMIT_GROCERY_ORDER = "submit_grocery_order"
    PREPARE_PAYMENT = "prepare_payment"
    COMMIT_PAYMENT = "commit_payment"


class ActionStatus(StrEnum):
    """The section 57 lifecycle: PREPARE, APPROVE, COMMIT, VERIFY.

    ``EXECUTED`` and ``VERIFIED`` are distinct on purpose (section 6): the
    external system accepting a request is not evidence the thing happened.
    """

    PREPARED = "prepared"
    NEEDS_APPROVAL = "needs_approval"
    APPROVED = "approved"
    EXECUTING = "executing"
    EXECUTED = "executed"
    VERIFIED = "verified"
    FAILED = "failed"
    CANCELLED = "cancelled"


#: Statuses from which an action may still be attempted externally. Anything
#: else has either finished or been abandoned.
LIVE_STATUSES: frozenset[ActionStatus] = frozenset(
    {
        ActionStatus.PREPARED,
        ActionStatus.NEEDS_APPROVAL,
        ActionStatus.APPROVED,
        ActionStatus.EXECUTING,
    }
)

#: Section 61: idempotency is mandatory for these. The rest may retry freely
#: because repeating them commits the user to nothing.
REQUIRES_IDEMPOTENCY: frozenset[ActionType] = frozenset(
    {
        ActionType.SEND_EMAIL,
        ActionType.BOOK_APPOINTMENT,
        ActionType.CANCEL_APPOINTMENT,
        ActionType.SUBMIT_GROCERY_ORDER,
        ActionType.PREPARE_PAYMENT,
        ActionType.COMMIT_PAYMENT,
    }
)

#: Section 57: these carry enough consequence that a human approves the exact
#: payload before it is committed.
REQUIRES_APPROVAL: frozenset[ActionType] = frozenset(
    {
        ActionType.BOOK_APPOINTMENT,
        ActionType.CANCEL_APPOINTMENT,
        ActionType.SUBMIT_GROCERY_ORDER,
        ActionType.PREPARE_PAYMENT,
        ActionType.COMMIT_PAYMENT,
    }
)


#: What each action does NOT authorise, rendered verbatim by the Approval
#: screen (section 58's mockup lists these as explicit crosses).
#:
#: The point is not decoration. Section 101 step 9 is "never authorize
#: repairs", and the way a human enforces that is by seeing it stated on the
#: screen where they say yes. An approval whose boundary is implicit invites
#: the reader to assume the adjacent thing was included.
NOT_AUTHORISED_BY: dict[ActionType, tuple[str, ...]] = {
    ActionType.BOOK_APPOINTMENT: (
        "Authorize repair work",
        "Authorize additional charges",
    ),
    ActionType.CANCEL_APPOINTMENT: ("Rebook at a different time",),
    ActionType.SUBMIT_GROCERY_ORDER: (
        "Change the order after submission",
        "Authorize substitutions beyond those listed",
    ),
    ActionType.PREPARE_PAYMENT: ("Send the payment",),
    ActionType.COMMIT_PAYMENT: (
        "Authorize any further payment",
        "Change the amount",
    ),
}


def authorised_scope(action_type: ActionType) -> tuple[str, tuple[str, ...]]:
    """What this action authorises, and what it explicitly does not.

    Returns ``(may, may_not)``. A type with no declared exclusions returns an
    empty tuple rather than a guess — inventing a denial would be as
    misleading as omitting a real one.
    """
    may = str(action_type).replace("_", " ").capitalize()
    return may, NOT_AUTHORISED_BY.get(action_type, ())


class Action(BaseModel):
    """One intended external write (section 60)."""

    model_config = ConfigDict(extra="forbid")

    id: str
    type: ActionType
    status: ActionStatus = ActionStatus.PREPARED

    idempotency_key: str
    payload_hash: str
    #: The exact request, kept so the approval screen can display what will
    #: happen rather than a summary of it (section 58).
    payload: dict[str, Any] = Field(default_factory=dict)

    task_id: str | None = None
    target_entity_id: str | None = None

    created_at: str
    attempt_count: int = Field(default=0, ge=0)
    last_attempt_at: str | None = None
    #: The provider's own identifier for what was created, and the evidence
    #: verification checks against.
    external_reference: str | None = None
    verification_state: VerificationState = VerificationState.PENDING

    failure_reason: str | None = None
    created_by_client: str | None = None

    @property
    def is_live(self) -> bool:
        return self.status in LIVE_STATUSES

    @staticmethod
    def make_id() -> str:
        return new_action_id()


class ActionDraft(BaseModel):
    """Input shape for preparing an action. No idempotency key: LifeOps
    generates it (section 61)."""

    model_config = ConfigDict(extra="forbid")

    type: ActionType
    payload: dict[str, Any] = Field(default_factory=dict)
    task_id: str | None = None
    target_entity_id: str | None = None


# --- pure rules ---------------------------------------------------------------


def payload_hash(payload: dict[str, Any]) -> str:
    """A stable hash of the exact request.

    Keys are sorted so two structurally identical payloads hash equal
    regardless of construction order — otherwise an approval would be
    invalidated by a dictionary reordering that changed nothing.
    """
    canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def make_idempotency_key(action_type: ActionType, payload: dict[str, Any]) -> str:
    """Derive the key LifeOps sends to the provider.

    Derived from the action type and payload rather than randomly generated,
    so a retry of the *same* intent reuses the key and the provider
    de-duplicates it. A random key per attempt would defeat the mechanism it
    is named for.
    """
    return f"{action_type}:{payload_hash(payload)}"


def requires_approval(action_type: ActionType) -> bool:
    return action_type in REQUIRES_APPROVAL


def prepare(draft: ActionDraft, *, now: str, client_id: str) -> Action:
    """Build the durable record that precedes the external request."""
    digest = payload_hash(draft.payload)
    return Action(
        id=Action.make_id(),
        type=draft.type,
        status=(
            ActionStatus.NEEDS_APPROVAL
            if requires_approval(draft.type)
            else ActionStatus.PREPARED
        ),
        idempotency_key=make_idempotency_key(draft.type, draft.payload),
        payload_hash=digest,
        payload=dict(draft.payload),
        task_id=draft.task_id,
        target_entity_id=draft.target_entity_id,
        created_at=now,
        created_by_client=client_id,
    )


def may_execute(action: Action) -> bool:
    """Whether an action is cleared to go out.

    An action needing approval is not cleared merely because it exists; the
    approval must have moved it to APPROVED first.
    """
    if action.type in REQUIRES_APPROVAL:
        return action.status is ActionStatus.APPROVED
    return action.status in {ActionStatus.PREPARED, ActionStatus.APPROVED}


def record_attempt(action: Action, *, now: str) -> Action:
    """Mark an attempt starting. Never blind-retry: the caller checks
    ``external_reference`` first (section 60)."""
    if not may_execute(action):
        raise ValidationError(
            f"action {action.id} is {action.status} and may not execute",
            action_id=action.id,
            status=str(action.status),
        )
    updated = action.model_copy(deep=True)
    updated.status = ActionStatus.EXECUTING
    updated.attempt_count += 1
    updated.last_attempt_at = now
    return updated
