"""Action outbox — every external write, recorded before it happens
(BUILD_SPEC sections 51, 57, 60, 61).

Section 60's rule is the reason this module exists: *never blind-retry an
external commitment*. Booking an appointment twice is worse than not booking
it, so an Action is persisted with its idempotency key **before** the request
goes out. If LifeOps dies mid-flight, the record is what tells the next run
whether the previous attempt may already have succeeded.

Two properties follow from that and are enforced here rather than by callers:

  * The idempotency key is generated by LifeOps, never by a model (section 61).
    A key an LLM invents is a key that changes when it re-reasons.
  * The payload hash is what an approval binds to (section 57). If the payload
    changes after approval, the hash changes, and the approval no longer
    matches — "material change invalidates approval" becomes arithmetic
    instead of judgement.
"""

from __future__ import annotations

import hashlib
import json
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from lifeops.domain.tasks import VerificationState
from lifeops.errors import ValidationError
from lifeops.ids import new_action_id


class ActionType(StrEnum):
    """The external actions of section 51.

    Narrow and semantic, never ``do_action``: a generic action tool moves the
    decision about what is safe out of policy and into a model's judgement.
    """

    SEND_EMAIL = "send_email"
    REQUEST_QUOTE = "request_quote"
    BOOK_APPOINTMENT = "book_appointment"
    CANCEL_APPOINTMENT = "cancel_appointment"
    PLACE_PHONE_CALL = "place_phone_call"
    BUILD_GROCERY_CART = "build_grocery_cart"
    SUBMIT_GROCERY_ORDER = "submit_grocery_order"
    PREPARE_PAYMENT = "prepare_payment"
    COMMIT_PAYMENT = "commit_payment"
    #: Section 72: "new payee always requires approval". Adding one is an
    #: action in its own right rather than a plain write, so it inherits the
    #: whole approval and audit path instead of a bespoke check.
    ADD_PAYEE = "add_payee"


class ActionStatus(StrEnum):
    """The section 57 lifecycle: PREPARE, APPROVE, COMMIT, VERIFY.

    ``EXECUTED`` and ``VERIFIED`` are distinct on purpose (section 6): the
    external system accepting a request is not evidence the thing happened.
    """

    PREPARED = "prepared"
    NEEDS_APPROVAL = "needs_approval"
    APPROVED = "approved"
    EXECUTING = "executing"
    EXECUTED = "executed"
    VERIFIED = "verified"
    FAILED = "failed"
    CANCELLED = "cancelled"


#: Statuses from which an action may still be attempted externally. Anything
#: else has either finished or been abandoned.
LIVE_STATUSES: frozenset[ActionStatus] = frozenset(
    {
        ActionStatus.PREPARED,
        ActionStatus.NEEDS_APPROVAL,
        ActionStatus.APPROVED,
        ActionStatus.EXECUTING,
    }
)

#: Section 61: idempotency is mandatory for these. The rest may retry freely
#: because repeating them commits the user to nothing.
REQUIRES_IDEMPOTENCY: frozenset[ActionType] = frozenset(
    {
        ActionType.SEND_EMAIL,
        ActionType.BOOK_APPOINTMENT,
        ActionType.CANCEL_APPOINTMENT,
        ActionType.SUBMIT_GROCERY_ORDER,
        ActionType.PREPARE_PAYMENT,
        ActionType.COMMIT_PAYMENT,
        ActionType.ADD_PAYEE,
    }
)

class RiskClass(StrEnum):
    """BUILD_SPEC section 56's risk ladder.

    The whole approval model hangs off this. Deriving "does a human decide?"
    from a declared risk class — rather than from a hand-maintained set of
    action types — means a new action cannot quietly land on the permissive
    side of the line: it has no risk class until someone assigns one, and
    ``risk_for_action`` refuses to guess.
    """

    R0_READ_ONLY = "R0"
    R1_REVERSIBLE = "R1"
    R2_EXTERNAL_COMMUNICATION = "R2"
    R3_EXTERNAL_COMMITMENT = "R3"
    R4_FINANCIAL_LEGAL_MEDICAL = "R4"


#: Section 56's table, action by action.
RISK_FOR_ACTION: dict[ActionType, RiskClass] = {
    # R2 — external communication. Says something on the user's behalf, but
    # commits them to nothing.
    ActionType.SEND_EMAIL: RiskClass.R2_EXTERNAL_COMMUNICATION,
    ActionType.REQUEST_QUOTE: RiskClass.R2_EXTERNAL_COMMUNICATION,
    ActionType.PLACE_PHONE_CALL: RiskClass.R2_EXTERNAL_COMMUNICATION,
    # R1 — a cart is reversible and commits nothing; section 56 puts only
    # *checkout* at R3.
    ActionType.BUILD_GROCERY_CART: RiskClass.R1_REVERSIBLE,
    # R3 — external commitment. Someone else now expects something.
    ActionType.BOOK_APPOINTMENT: RiskClass.R3_EXTERNAL_COMMITMENT,
    ActionType.CANCEL_APPOINTMENT: RiskClass.R3_EXTERNAL_COMMITMENT,
    ActionType.SUBMIT_GROCERY_ORDER: RiskClass.R3_EXTERNAL_COMMITMENT,
    # R4 — money.
    ActionType.PREPARE_PAYMENT: RiskClass.R4_FINANCIAL_LEGAL_MEDICAL,
    ActionType.COMMIT_PAYMENT: RiskClass.R4_FINANCIAL_LEGAL_MEDICAL,
    # Section 56 lists "New payee" at R4, "Approval always" — the same rung as
    # the payment itself, because an unnoticed payee is how a later payment
    # goes somewhere nobody chose.
    ActionType.ADD_PAYEE: RiskClass.R4_FINANCIAL_LEGAL_MEDICAL,
}

#: Section 56 marks R2 "policy-controlled", and the table's shape decides the
#: default: R3 reads "Approval initially", R4 "Approval always", R2 neither.
#: Section 101 settles it — the Electrician scenario has Hermes contact
#: providers, collect availability, and collect a diagnostic fee on its own,
#: and only requests approval at the booking (step 11). Gating every quote
#: request behind a human would make that scenario unusable.
#:
#: It stays a named constant rather than an inlined False because section 56
#: calls it policy-controlled: a user who wants to see every outbound message
#: flips this, and R3/R4 are unaffected either way.
REQUIRE_APPROVAL_FOR_EXTERNAL_COMMUNICATION = False

#: R3 and R4 are never policy-controlled. Section 56: "Approval initially" and
#: "Approval always" respectively.
ALWAYS_APPROVED: frozenset[RiskClass] = frozenset(
    {RiskClass.R3_EXTERNAL_COMMITMENT, RiskClass.R4_FINANCIAL_LEGAL_MEDICAL}
)


def risk_for_action(action_type: ActionType) -> RiskClass:
    """The risk class of an action. Raises rather than defaulting.

    An unclassified action is a gap in the safety model, and defaulting it to
    anything — least of all the permissive end — would hide that.
    """
    try:
        return RISK_FOR_ACTION[action_type]
    except KeyError:
        raise ValidationError(
            f"no risk class declared for action type {action_type!r}",
            field="type",
        ) from None


#: Kept as a derived view so existing callers and tests keep working.
REQUIRES_APPROVAL: frozenset[ActionType] = frozenset(
    action_type
    for action_type, risk in RISK_FOR_ACTION.items()
    if risk in ALWAYS_APPROVED
    or (
        risk is RiskClass.R2_EXTERNAL_COMMUNICATION
        and REQUIRE_APPROVAL_FOR_EXTERNAL_COMMUNICATION
    )
)


#: What each action does NOT authorise, rendered verbatim by the Approval
#: screen (section 58's mockup lists these as explicit crosses).
#:
#: The point is not decoration. Section 101 step 9 is "never authorize
#: repairs", and the way a human enforces that is by seeing it stated on the
#: screen where they say yes. An approval whose boundary is implicit invites
#: the reader to assume the adjacent thing was included.
NOT_AUTHORISED_BY: dict[ActionType, tuple[str, ...]] = {
    ActionType.BOOK_APPOINTMENT: (
        "Authorize repair work",
        "Authorize additional charges",
    ),
    ActionType.ADD_PAYEE: (
        "Pay this payee",
        "Change an existing payee's details",
    ),
    ActionType.CANCEL_APPOINTMENT: ("Rebook at a different time",),
    ActionType.SUBMIT_GROCERY_ORDER: (
        "Change the order after submission",
        "Authorize substitutions beyond those listed",
    ),
    ActionType.PREPARE_PAYMENT: ("Send the payment",),
    ActionType.COMMIT_PAYMENT: (
        "Authorize any further payment",
        "Change the amount",
    ),
}


def authorised_scope(action_type: ActionType) -> tuple[str, tuple[str, ...]]:
    """What this action authorises, and what it explicitly does not.

    Returns ``(may, may_not)``. A type with no declared exclusions returns an
    empty tuple rather than a guess — inventing a denial would be as
    misleading as omitting a real one.
    """
    may = str(action_type).replace("_", " ").capitalize()
    return may, NOT_AUTHORISED_BY.get(action_type, ())


class Action(BaseModel):
    """One intended external write (section 60)."""

    model_config = ConfigDict(extra="forbid")

    id: str
    type: ActionType
    status: ActionStatus = ActionStatus.PREPARED

    idempotency_key: str
    payload_hash: str
    #: The exact request, kept so the approval screen can display what will
    #: happen rather than a summary of it (section 58).
    payload: dict[str, Any] = Field(default_factory=dict)

    task_id: str | None = None
    target_entity_id: str | None = None

    created_at: str
    attempt_count: int = Field(default=0, ge=0)
    last_attempt_at: str | None = None
    #: The provider's own identifier for what was created, and the evidence
    #: verification checks against.
    external_reference: str | None = None
    verification_state: VerificationState = VerificationState.PENDING

    failure_reason: str | None = None
    created_by_client: str | None = None

    @property
    def is_live(self) -> bool:
        return self.status in LIVE_STATUSES

    @staticmethod
    def make_id() -> str:
        return new_action_id()


class ActionDraft(BaseModel):
    """Input shape for preparing an action. No idempotency key: LifeOps
    generates it (section 61)."""

    model_config = ConfigDict(extra="forbid")

    type: ActionType
    payload: dict[str, Any] = Field(default_factory=dict)
    task_id: str | None = None
    target_entity_id: str | None = None


# --- pure rules ---------------------------------------------------------------


def payload_hash(payload: dict[str, Any]) -> str:
    """A stable hash of the exact request.

    Keys are sorted so two structurally identical payloads hash equal
    regardless of construction order — otherwise an approval would be
    invalidated by a dictionary reordering that changed nothing.
    """
    canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def make_idempotency_key(action_type: ActionType, payload: dict[str, Any]) -> str:
    """Derive the key LifeOps sends to the provider.

    Derived from the action type and payload rather than randomly generated,
    so a retry of the *same* intent reuses the key and the provider
    de-duplicates it. A random key per attempt would defeat the mechanism it
    is named for.
    """
    return f"{action_type}:{payload_hash(payload)}"


def requires_approval(
    action_type: ActionType,
    *,
    approve_external_communication: bool = REQUIRE_APPROVAL_FOR_EXTERNAL_COMMUNICATION,
) -> bool:
    """Whether a human decides this one (section 56).

    R3 and R4 always. R2 by policy. R0 and R1 never — section 56 marks a
    calendar hold automatic, and a hold is not a booking (section 63).
    """
    risk = risk_for_action(action_type)
    if risk in ALWAYS_APPROVED:
        return True
    if risk is RiskClass.R2_EXTERNAL_COMMUNICATION:
        return approve_external_communication
    return False


def prepare(draft: ActionDraft, *, now: str, client_id: str) -> Action:
    """Build the durable record that precedes the external request."""
    digest = payload_hash(draft.payload)
    return Action(
        id=Action.make_id(),
        type=draft.type,
        status=(
            ActionStatus.NEEDS_APPROVAL
            if requires_approval(draft.type)
            else ActionStatus.PREPARED
        ),
        idempotency_key=make_idempotency_key(draft.type, draft.payload),
        payload_hash=digest,
        payload=dict(draft.payload),
        task_id=draft.task_id,
        target_entity_id=draft.target_entity_id,
        created_at=now,
        created_by_client=client_id,
    )


def may_execute(action: Action) -> bool:
    """Whether an action is cleared to go out.

    An action needing approval is not cleared merely because it exists; the
    approval must have moved it to APPROVED first.
    """
    if action.type in REQUIRES_APPROVAL:
        return action.status is ActionStatus.APPROVED
    return action.status in {ActionStatus.PREPARED, ActionStatus.APPROVED}


def record_attempt(action: Action, *, now: str) -> Action:
    """Mark an attempt starting. Never blind-retry: the caller checks
    ``external_reference`` first (section 60)."""
    if not may_execute(action):
        raise ValidationError(
            f"action {action.id} is {action.status} and may not execute",
            action_id=action.id,
            status=str(action.status),
        )
    updated = action.model_copy(deep=True)
    updated.status = ActionStatus.EXECUTING
    updated.attempt_count += 1
    updated.last_attempt_at = now
    return updated
